export default {
  computed: {
    fieldsInfo () {
      return [
        {
          text: this.$t('fields.id'),
          name: 'id',
          details: false,
        },
        {
          type: 'input',
          column: 'lastName',
          text: this.$t('fields.lastname'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'lastName',
          multiedit: false,
        },
        {
          type: 'input',
          column: 'firstName',
          text: this.$t('fields.firstname'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'firstName',
          multiedit: false,
        },
        {
          type: 'input',
          column: 'nickname',
          text: this.$t('fields.nickname'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'nickname',
          required: false,
        },
        {
          type: 'input',
          column: 'additionalName',
          text: this.$t('fields.additionalName'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'additionalName',
          required: false,
        },
        {
          type: 'input',
          column: 'arFirstName',
          text: this.$t('fields.arFirstName'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'arFirstName',
          required: false,
        },
        {
          type: 'input',
          column: 'arLastName',
          text: this.$t('fields.arLastName'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'arLastName',
          required: false,
        },
        {
          type: 'input',
          column: 'arNickname',
          text: this.$t('fields.arNickname'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'arNickname',
          required: false,
        },
        {
          type: 'input',
          column: 'arAdditionalName',
          text: this.$t('fields.arAdditionalName'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'arAdditionalName',
          required: false,
        },
        {
          type: 'select',
          url: 'api/Countries',
          list: {
            value: 'id',
            text: 'name',
            data: [],
          },
          column: 'nationality',
          text: this.$t('fields.nationality'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'nationality',
          apiObject: {
            name: 'nationality.name',
          },
        },
        {
          type: 'select',
          url: 'api/sexes',
          list: {
            value: 'id',
            text: 'name',
            data: [],
          },
          column: 'sex',
          text: this.$t('fields.sex'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'sex',
          apiObject: {
            name: 'sex.name',
          },
        },
        {
          type: 'input',
          column: 'details',
          text: this.$t('fields.details'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'details',
          required: false,
        },
        {
          type: 'input',
          column: 'arDetails',
          text: this.$t('fields.arDetails'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'arDetails',
          required: false,
        },
        
        {
          type: 'input',
          column: 'personalNumber',
          text: this.$t('fields.personalNumber'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'personalNumber',
          multiedit: false,
          required: false,
        },
      ]
    },
  },
}
